// front-end/src/app/app.component.ts
import { Component } from '@angular/core';
import { Ng4LoadingSpinnerService } from 'ng4-loading-spinner';
import { NgForm } from '@angular/forms';
import { SendDataService } from './services/send-data.service';
import { FlashMessagesService } from 'angular2-flash-messages';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  messgaeError={email:[],name:[],password:[]};
myFile:File;
fileselect:boolean=false;
  constructor(private spinnerService: Ng4LoadingSpinnerService ,private sendData:SendDataService,
    private flashMessagesService: FlashMessagesService) { }
  ngOnInit() {
  }
  
  fileEvent($event){
    console.log( $event.target.files[0]);
        this.fileselect=true;
        this.myFile = $event.target.files[0];
}
  onSignup(form: NgForm) {
    const email = form.value.email;
    const password = form.value.password;
    const username= form.value.username;
    if (!this.validateFile(this.myFile.name)) {
      console.log('Selected file format is not supported');
      this.flashMessagesService.show('Selected file format is not supported'
        , { cssClass: 'alert-danger', timeout: 1000 });
      return false;
  }
  else
  {
    let formData = new FormData();
    formData.append("email", email);
    formData.append("password", password);
    formData.append("name", username);
    formData.append("image", this.myFile,this.myFile.name);
    this.sendData.Send(formData).subscribe(data=>{
      this.spinnerService.hide();
      console.log("data",data)
      this.flashMessagesService.show("Data Sended"
        , { cssClass: 'alert-success', timeout: 1000 });

    },
  error=>{
    this.spinnerService.hide(); 
    console.log("error",error.error)
    
    //this.messgaeError=error.error.errors;
    this.flashMessagesService.show(error.error.message
      , { cssClass: 'alert-danger', timeout: 1000 });
  });
} 
  }
  validateFile(name: String) {
    var ext = name.substring(name.lastIndexOf('.') + 1);
    if (ext.toLowerCase() == 'png'||ext.toLowerCase() == 'bmp'||ext.toLowerCase()=="jpg"||ext.toLowerCase() == 'gif') {
        return true;
    }
    else {
        return false;
    }
}

}

<div class="formulaire">      
  <div class="panel panel-default"> 
      <div class="panel-heading">
          <div class="text-center">
              <h1>
                formulaire
              </h1>
            </div>
            <ng4-loading-spinner> </ng4-loading-spinner>
            <flash-messages></flash-messages>
      </div>   
        <form class="was-validated form-signin panel-body" (ngSubmit)="onSignup(f)"  #f="ngForm">


            <div class="text-center mb-4">
            </div>
            <div class="form-label-group">
                <label for="email">Username</label>
                <input type="text" id="username" name="username" ngModel class="form-control"  #username="ngModel" required>
                <div class="alert alert-danger" *ngIf="username.errors && (username.dirty || username.touched)" >
                    <div [hidden]="!username.errors.required" >
                    username is required
                      </div>
                </div>
                <div class="alert alert-danger" *ngIf="messgaeError.name?.length > 0" >
                  <div *ngFor='let nameError of messgaeError.name'>  
                  {{nameError}}
                </div>
              </div>
            <div class="form-label-group">
              <label for="email">Email</label>
              <input type="email" id="email" name="email" ngModel class="form-control"  #email="ngModel" required pattern="[^ @]*@[^ @]*">
              <div class="alert alert-danger" *ngIf="email.errors && (email.dirty || email.touched)" >
                  <div [hidden]="!email.errors.required" >
                      email is required
                    </div>
                    <div [hidden]="!email.errors.pattern">
                      email is invalid
                    </div>
              </div>
              <div class="alert alert-danger" *ngIf="messgaeError.email?.length > 0" >
                  <div *ngFor='let emailError of messgaeError.email'> 
                  {{emailError}}
                </div>
              </div>
            </div>
          
            <div class="form-label-group">
              <label for="password">Password</label>
              <input
                type="password"
                id="password"
                name="password"
                ngModel
                #password="ngModel"
                class="form-control" required minlength="6">
                <div *ngIf="password.errors && (password.dirty || password.touched)" class="alert alert-danger">
                    <div [hidden]="!password.errors.required">
                      password is required!
                    </div>
                    <div [hidden]="!password.errors.minlength">
                      password must be at least 6 characters long.
                    </div>
                    <div class="alert alert-danger" *ngIf="messgaeError.password?.length > 0" >
                        <div *ngFor='let passwordError of messgaeError.password'></div>  
                        {{passwordError}}
                      </div>
                    </div>
                  </div>
            </div>
            <div class="form-label-group">
              <label for="passwordConfirmation">Password Confirmation</label>
              <input
                type="password"
                id="passwordConfirmtion"
                name="passwordConfirmation"
                ngModel
                #passwordConfirmation="ngModel"
                class="form-control" required min minlength="6">
                <div *ngIf="(passwordConfirmation.value!=password.value)&&passwordConfirmation.touched" class="alert alert-danger">
                    <span>
                      is not mutched
                    </span>
                  </div>
            </div>
            <label for="validatedCustomFile">Select Photo</label>
            <div class="custom-file form-label-group">
              <input type="file" class="custom-file-input" id="validatedCustomFile" accept="image/*" 
              #fileupload name="myFile" (change)="fileEvent($event)" required>
              <label class="custom-file-label" for="validatedCustomFile" >Choose file...</label>
              <div class="invalid-feedback">Photo not Select</div>
            </div>
            <br>
            <br>
            <button class="btn btn-lg btn-primary btn-block"   type="submit" [disabled]="!f.valid||(passwordConfirmation.value!=password.value)||!fileselect">Send</button>
       </form>
</div>
</div>

// vuejsFront/src/App.vue
<template>
  <div id="app">
  <div style="margin-top:40px" class="container">
  <div class="text-left">
  <flash-message class="myCustomClass"></flash-message>
  </div>
  </div>
  <div class="formulaire">      
  <div class="panel panel-default"> 
      <div class="panel-heading">
          <div class="text-center">
              <h1>
                formulaire
              </h1>
            </div>
      </div>
    <form class=" was-validated form-signin panel-body"  @submit.prevent="onSubmit">
    <div class="form-label-group" :class="{error: errors.has('username')}">
      <div class="text-left">
      <label>Username</label>
      </div>
      <input type="text" name="username" autofocus class="form-control" placeholder="Username" v-validate="'required'" v-model="username">
      <div class="text-left">
      <div class="alert alert-danger" v-if="errors.has('username')">{{errors.first('username')}}</div>
      </div>
    </div>
    <div class="form-label-group" :class="{error: errors.has('email')}">
      <div class="text-left">
      <label>Email</label>
      </div>
      <input type="email" name="email"   class="form-control" placeholder="Email" v-validate="'required|email'" v-model="email">
      <div class="text-left">
      <div class="alert alert-danger" v-if="errors.has('email')">{{errors.first('email')}}</div>
      </div>
    </div>
    <div class="form-label-group" :class="{error: errors.has('password')}">
      <div class="text-left">
      <label>password</label>
      </div>
      <input type="password" name="password" autofocus  class="form-control" placeholder="password" v-validate="'required|min:6'" v-model="password">
      <div class="text-left">
      <div class="alert alert-danger" v-if="errors.has('password')">{{errors.first('password')}}</div>
      </div>
    </div>
    <div class="text-left">
      <label>Select Photo</label>
      </div>
    <div class="custom-file form-label-group">
    <input  type="file" class="custom-file-input" id="validatedCustomFile" accept="image/*" 
               name="myFile" @change="onFileChanged" v-validate="'required'">
              <label class="custom-file-label" for="validatedCustomFile">Choose file...</label>
              <div class="invalid-feedback">Photo not Select</div>
    </div>
    <button type="submit" :disabled="errors.any()||(username==''||email==''||password=='')" class="btn btn-lg btn-primary btn-block">Send</button>
  </form>
  </div>
  </div>
  </div>
</template>

<script>
import axios from 'axios'
require('vue-flash-message/dist/vue-flash-message.min.css');
export default {
  name: 'app',
  data() {
    return {
      email: '',
      username:'',
      password:'',
      image:''
    }
  },
  methods: {
     onFileChanged (event) {
     this.image= event.target.files[0]
     console.log(this.image)
  },
    onSubmit() {
      this.$validator.validateAll()
      
      if (!this.errors.any()) {
        const formData = new FormData()
   formData.append("email", this.email);
    formData.append("password",this.password);
    formData.append("username", this.username);
    formData.append("image", this.image,this.image.name);
        axios.post(`http://localhost:8000/api/trello`, {
      body:formData
    },
  )
    .then(response => {
      console.log("data sended",response)
     this.flash('data sended', 'success', {
  timeout: 2000,
});
    })
    .catch(e => {
       console.log("error",e)
       this.flash('Validation failed', 'error', {
  timeout: 2000,
});
    })
      }
    }
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
.form-signin {
    width: 100%;
    max-width: 420px;
    padding: 15px;
    margin: 0 auto;
}
.form-label-group{
    margin-bottom: 10px;
}
.formulaire{
    padding:80px;
    min-height:100vh;
    width: auto;
    height: auto;
}

.panel{
    background: white;
    border-radius: 1%;
    max-width: 440px;
    margin: 0 auto;
    padding-top: 20px;
    opacity: 0.85;
    filter: Alpha(opacity=85)
}
</style>
